---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rancher
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`longhorn.lab.oscarr.nl`)
      services:
        - name: longhorn-ui
          port: 80
