cluster:
  # backups:
  #   enabled: true # TODO
  databases:
    - name: app
      ensure: present
      owner: app
      schemas:
        - name: groupironman
          owner: app
          ensure: present
  cluster:
    initdb:
      postInitApplicationSQL:
        - |
          CREATE TABLE IF NOT EXISTS groupironman.groups(
                  group_id BIGSERIAL UNIQUE,
                  group_name TEXT NOT NULL,
                  group_token_hash CHAR(64) NOT NULL,
                  PRIMARY KEY (group_name, group_token_hash)
            );
