---
apiVersion: v1
kind: ConfigMap
metadata:
  name: html-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <style>
        /* Add some style to the buttons */
        .button {
          background-color: #4CAF50;
          color: white;
          padding: 15px 20px;
          margin: 8px 0;
          border: none;
          cursor: pointer;
          width: 100%;
        }

        .button:hover {
          background-color: #45a049;
        }
      </style>
    </head>
    <body>
      <!-- Add the buttons -->
      <button class="button" onclick="window.location.href = 'https://hetmagkapot.nl';">Het mag Kapot</button>
      <button class="button" onclick="window.location.href = 'https://ishetkapot.nl';">Is het kapot?</button>
    </body>
    </html>
