---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vikunja
  namespace: vikunja
spec:
  encryptedData:
    dex-client-secret: AgBI9py78LYRAgkfW46Rilae/Zs7EX+NLW+u5ncuFWKNAmacsHxIXzOoQd8qoMlY38CIOyylxcWZueSTGAWeIyNvPZ3s0Z2koGml/3g+ekGtNIFpWhQpEiw+EvcMY/ZfnCmjCdlrUgGA/UFCCywCng/PHnHWxGIijV5Yfis5jKj/F7Aa+b6SB5O1LWbIGoj0iVym35RUeaexIgFegc92QTjDh+PMbMw3Ce0Sqv8O1TaWv3FzP3gdkiq8ssDohcbjBm5glLT+jjAGJCUhvBQRUhCtmnXNdsDdsPN8H0r0DjtJ4zM+gRu6hvLk0YLK1+azCj5mCJ/XRkUNTohKiHkxuMUsr5Cwxo37rcqrsWgnEziaLenXgmINYmLZkMFdu+VCKkRIjDs8aNY+WoWlIrpvD2tjheIkxe3U7RSdMUq5dpfA2IlBqs9LCm2YFPoraG2A+NLGpEdvXSr262SpGGnYTzhDGsO9wY2W3zA4l4nTjScW4EbNDFKkRYwfYioI8L1QSLBhVDgZzsje3M7RhYpjjYIeqpM2chG0edvMNNaWuy4g7y3cAtZgec5VXZvJRpImzUMQKo1qIB7wVexj3+PrTk7oxMpPd4OSn7IQ8ahgYY6yd2C7KUF1Gbn0ndGCrhkC2Emh3xlvzEung0asH16aRzyulQxOfGIe4dNZGUPnArNC4aZrP1ByIXVzBd+4DR+IZANAFcC9rg96fr59yLiey+gskevEiUx9E1Cyz79kII/3F49vpg==
