---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: drinkn
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ['missingkey=invalid']
  generators:
    - pullRequest:
        github:
          owner: bierteam
          repo: drinkn
          tokenRef:
            secretName: github-token
            key: token # prevent rate limiting
          labels:
            - preview
        requeueAfterSeconds: 1800
  template: # https://argo-cd.readthedocs.io/en/release-2.7/operator-manual/applicationset/Generators-Pull-Request/#template
    metadata:
      name: 'drinkn-pr-{{ .number }}'
      labels:
        app.kubernetes.io/instance: drinkn
      annotations:
        link.argocd.argoproj.io/external-link: 'https://github.com/bierteam/drinkn/pull/{{ .number }}'
    spec:
      destination:
        namespace: 'drinkn-pr-{{ .number }}'
        name: 'in-cluster'
      project: restricted
      source:
        repoURL: 'https://github.com/bierteam/drinkn.git'
        targetRevision: '{{ .branch }}'
        path: charts/drinkn
        helm:
          parameters:
            - name: image.tag
              value: 'sha-{{ .head_short_sha_7 }}'
            - name: fqdn
              value: 'drinkn-pr-{{ .number }}.lab.oscarr.nl'
            - name: pr.enabled
              value: 'true'
            - name: pr.number
              value: '{{ .number }}'
            - name: pr.ref
              value: '{{ .branch }}'
            - name: replicas
              value: '1'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            pod-security.kubernetes.io/warn: restricted
            pod-security.kubernetes.io/enforce: baseline
          #   argocd.argoproj.io/instance: my-argocd-application-name
          # annotations:
          #   argocd.argoproj.io/tracking-id: >-
          #     drinkn-pr-{{ .number }}:app/Namespace:drinkn-pr-{{ .number }}/drinkn-pr-{{ .number }}
        syncOptions:
          - CreateNamespace=true
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-token
  namespace: argocd
  annotations:
    a8r.io/description: "Expires on Thu, Aug 5 2027. https://github.com/settings/tokens?type=beta"
spec:
  encryptedData:
    token: AgAgY9bXCM6EeRcsnMVAEPwqFMifJ4dypjzpNgg6dGhjcnMRTH/NJUSPoxsCMZDGjxTDKBHi+DgYgbS65jyK3Mccw+4GpnEESEH7qFWY5nDapT5y0+kZTwxpUaqKG4gmHcksPy4r1B8Ae/cmpAZr0/zlPT50H2lJBUAGGd+Cbiidqy3J6fEvVlz/Ibv/n4vxQ+gTVFwKSLVt4e/MzbxPJTNOOFnmABL+waiaTYT7hEQMey6smrjlOEmRqunc2gH0bgnwdrGr3M7E4a2FM87Ua9AOPEb9zCWpQmkHG6ZTvgBvtXe8cUc1oDXa34WNDOoemyG6gdXBDTqrg3QcuNZPFTd/mU1Sx5qLNgEf6+WMHwRClpAmt/M/ntKMU8yUSuOwQ4WCK0QctM3lX/x3d+M83XF3r3SnwIHkvQPl+6/nt8zrwyuARnEFSSI2Klj4g1WofU4qZ/BHqQYNBgMIVP2d69jEgF/akuhLFjLEHDTZvLG5MunYZNAi7NlYGaoRkeCq1kz5Drs/YOUNTwrqg9uBiyCcNJZzhl6+oCIM3h2+xaUUQ5zeMP+kLsUiqP7GMgCUbOEMi/+CZYwUHOXADTZ/gRGeKpUn/t6zETEFjSsr6TZzBlS6ahyNP6+qu3qCt9tcf54krB73dKezTD6VBwVoTqXgqsUFg+GzRBSsBdd/2KlCoqh+/cPA2x5fU23vVS3MRaPmQaEIAnqGAuIroXZptRyoHBcQmztuA2pqXt1ued3m40X4zl65qu3QNUhwgaof2RnIGCTHLIgBCs0TPd/d/PkevLEdJd9vCjU+xHwfC/CBiYPQbiwU+9PcGw41uyg=
