apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare
  namespace: external-dns
spec:
  encryptedData: 
    token: AgCOZyASQpy6OXUus2NxheUQE8iUsF0rGLllx5rcyYdm3JHiF+pH1EqNGHAudRK3rj/x4hSLTcKBBKCgetz70Le61W5P3n53DOPqekf9pNv5rHD4AZfnVN2fKTtTvmIxMjINEKVg9oA179gAE0Rv3gnWauG0fSJDoWQadBUV2HNhiQMmlSqGSJwSSK36Ykn2BMrKtz/PXLDzna8y82YtcIipDp3uvsWibXmJaESbPMxbNQfDXlxQTe7gQZ2e9sH5ILGmOhvWuHVShLeh0in+qVnSd9XPFkRjf6q31mPyiSQDMN+XEoPNAiCaXonY9sYNonWzat4TUXW6Jxhe92KYwRuTCcgVybKM3tkKsrQWDNJF1h1bfHOgxC5nk31nLvCbyhmkLi2IxuVifIBYjzkig0mBJiYZu+p9BR5kxw4xuLFJs5PmWi6p4T+ofTK/W7hvuNyPSsu1xcAqA29RgE5pVUkQSZKrzmVKX4gjm99NCDDOeoX8IrKRSefSilu/R7Rs3W9rWo+XMkGIMduIyFkgasmChOKux8zPftcWTNKlUxmSg3gsnZvIZVM/dVvOUhBcGEIfLmrukSG8fuq9nPaUl2Y3wEgvFOWkgq39IqE0xyb6QZ8v/XsHuzLLK9gLRXTKjUTdjXGwe/iWhB117GowBx3vLBaHC7yb9+uABQje1t/1ueI5Pxjm9yIN5Byj9B7ISm3u2rgIqnZMZgGLqR+X5wAlrM0bbWt7Mih/0sctxtwpFuZ7lFf4p8YF
