---
apiVersion: v1
kind: ConfigMap
metadata:
  name: security-txt
data:
  security.txt: |
    -----BEGIN PGP SIGNED MESSAGE-----
    Hash: SHA256

    # This is the security.txt file for everything in our kubernetes cluster
    # It is defined in this repo https://github.com/bierteam/uber-kubernetes

    Contact: mailto:security@oscarr.nl
    Contact: https://github.com/bierteam/uber-kubernetes/security/advisories/new
    Expires: 2026-04-27T22:00:00.000Z
    Encryption: https://keybase.io/oscrx/key.asc
    Preferred-Languages: nl, en
    Canonical: https://oscarr.nl/.well-known/security.txt
    Acknowledgments: https://github.com/bierteam/uber-kubernetes/blob/main/SECURITY.md
    Policy: https://github.com/bierteam/uber-kubernetes/blob/main/SECURITY.md

    # Easily check the signature at: https://keybase.io/verify
    -----BEGIN PGP SIGNATURE-----

    iQIzBAEBCAAdFiEEpwez+rJ156oyNxEKZLg5wX4x8VEFAmRL8RoACgkQZLg5wX4x
    8VEMzhAAz2HgWV8us5RHMeDKg+AP9YvS4/KdhSVXfmwVsfQ9sv1U7NNPjT9jrj9M
    EaAQdOUmZJJjx+Xr4FRP9RM7lsV0OXZLStmb0uhlrPYnPTEEq9pu9b3G+7WF9kit
    mcvJjQ9iBJUdhPP7gSbOhQHy0y17x0MkbeR4T+XRMKsOijobDQHVpnJrNStTIPLl
    VdKL5O7FM6FCoonrXGnrtGVzXm5+imxW8XbQH9aB4tDSiDCtog7h8WdcWT/ZRikl
    GVV1Rhqwgl0gVLfl1SkWT4v+H+8+UvO9IztgGn/U1ZKKNsGxtBf/eZrSpwoKLltu
    FwJA02T4wpJNU19ghF0wL08PnioIFI7nP0IVK/ORi3fyZ9UsCRIIRmDKdcmrNBPs
    ns/2yQSNX2j4tzUldkLI4q0DrZLovrGV7RfJEw6pvty/noyDMNe5CWk0c7aRWU/s
    lakYv0hUqkUVZV9c5+gOjdq+QwHQFgq6TItsMCpaZU1GYmv9+EgQspVE/bRotg2R
    qS+FM8a4UwtiaL49duHa8Io2pqieZeYexlPNew9yD+JKB4yX6hoD803UIIEbaIgu
    EjbkhEoDhsbK8bSQrEKRnPdUz7u8NIie+rkRBYOp4jd3PaKj/1oi5nLjM2idpBsh
    Yz+wYeKJvAY2OYEDKZB/xg40mqMm9WnrITmFfvcq8Jx1x3VSsk0=
    =NJwf
    -----END PGP SIGNATURE-----
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-txt
spec:
  selector:
    matchLabels:
      app: security-txt
  replicas: 2
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: security-txt
    spec:
      containers:
        - name: nginx
          image: joseluisq/static-web-server:2.16.0
          ports:
            - containerPort: 80
          volumeMounts:
            - name: security-txt
              mountPath: /public/.well-known/
          resources:
            requests:
              cpu: "10m"
              memory: "16Mi"
            limits:
              cpu: "10m"
              memory: "16Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: security-txt
          configMap:
            name: security-txt
            items:
            - key: security.txt
              path: security.txt
---
apiVersion: v1
kind: Service
metadata:
  name: security-txt
spec:
  selector:
    app: security-txt
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: security-txt
spec:
  entryPoints:
    - websecure
  routes:
    - match: Path(`/.well-known/security.txt`)
      kind: Rule
      priority: 100 # high prio to overwrite any ingressroute
      middlewares:
        - name: security-txt
      services:
        - name: security-txt
          port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: security-txt
spec:
  redirectRegex:
    regex: .*
    replacement: https://oscarr.nl/.well-known/security.txt
