---
# https://docs.siderolabs.com/kubernetes-guides/csi/local-storage
apiVersion: v1alpha1
kind: UserVolumeConfig
name: local-path-provisioner
provisioning:
  diskSelector:
    match: system_disk
  minSize: 20GiB
