---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgA9zL1ZDSsx33nm32kvjtckQrBvGzBYvHzy5YPoGp3fG8tGdL1+jYh9xr9aZUrpj1vYEx1LGTFYoNSkKTzY8seOkVcxndbuo2sBN3xKtl2cDlw8zeBY9k+SqVi1o8TK0k3PV4895PQcesDgAwT39Xl+x1UAZkoR4ibCMnW/1lVL8BxdEFUCM6mJ9g9kv3Z11fdIwCJ9fnxp+Png4P0xhBjHkvS9g8rDm/F+ijiYV93AgWAgv8vQI1SCXppo+rzeChrmqsXifbnZu2x/QafkBewFtYOns0hf75yGIKXXxEmmCa6jEM5bmIVXkICy6jCl90Rut44WzlAviAuwYXFpweEEEIzeNZwaa2OGFSEI/RuJIGod8QiqfWf550iFVjUa3gU9TNK/evxo2AD2wVVnvBpzrf6AJjMOdl2cnj+nX0LJjiyIN1sMsFF3BDKvxTNdd/cG+suz0AJhWQbT8uCNGPGT9mFLuvpwhqT3bv2kjGom98SGWK4hZtoS6SiJrwE9E54P0NiZ0XDbhmTdUc9F9dyZJ4IqI2vCITXnMVFP5J7lyvACrsy1TnMXWci6clZVJW2p0moDNQxaMerehixJ5qkSPIqIaJVvDv68FhC5O+KjlfI4inOvwEUVCHE68nES70rdbQhQDIfHC8ZC7GIN+O4lQA/TmU8gQWENTZR/zwGFaQQ/7gqazyHq4+t1df+CMvuFE9e+ocgJTBgBxp0TbsPbZY5NSIFv/SU4J/AJSMuERTm2VUptH72u
