---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBzmXH2aeXav0bsxUxG+idyxgd9bPbimoJGfJdMBrV1iI4ypO//6VC/sn1JUWMToswt66XnzwNplWNhGhoi/HuwQKpluvvgFp8Hs28rvt0WYd+C7EG733irH6iRzNPkP0DBSnaSEkKBvS1hhprLfYHBUDX9gjfsh0szyOcfTO9Q2i4jXUh5QwaHBEHRV43uAa5LsHJJSg2XOUpZQd6s/Aq7bzWcMCQ/jLipU/Kpf6ZUDLLW5OzcV5cISDCpFKcwjJi9GNFyQrf8dpyDwr+28BTwO3eIbvJMFtEwGzLFwUMkJNtGWIbXLzJrOsIZun8uJvX5d4seA6wppGjO18YkCqdFgOY76yLVFIaZJgsDyY/IBsMDrU+CF20bjzM3C+h36TuMjT95s5KlUBgj84qybLLXRTQ2Ck+6PdBapu8Ubf+eAbHdQSWBFnqeTVB7L02/pfT6fz5CPiaKGT2AhIYmiTIiDLmmi7OmAzkPERQF3Jn9Ka+x1NUCJ5cQnpGu+SicrNJAqgjPmYy03d9yXLSCilacGYjectRDSjBhGdTBEnEiMoj6ifIYUX45a8U2jebNOOmUYpo1TyTbog9B/w9POI80ISVJIOFaG6VA47yh4y7fhUF6bzkT83s1GLEQrW/dOLfSI5PKBRJrC7z8Myu3qENxI2tmyHqHd+tHPEzGwmD/RLnykdkvbEnpk8/tLKAk/KBHClP+XVGD7F6jZjIPgHeTatLI2OVAOVeRK6VFWwLjc0w6V76Id93a
