---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: devopscar-nl
spec:
  secretName: devopscar-nl-tls
  issuerRef:
    name: letsencrypt
    kind: Issuer
  privateKey:
    rotationPolicy: Always
    algorithm: ECDSA
  dnsNames:
    - "devopscar.nl"
    - "*.devopscar.nl"
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-tls-devopscar-nl
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`fake`)
      kind: Rule
      services:
        - name: noop@internal
          kind: TraefikService
  tls:
    secretName: devopscar-nl-tls
    domains:
      - main: "devopscar.nl"
      - sans: ["*.devopscar.nl"]
