{{- range $domain := .Values.domains }}
{{- $noDotsDomain :=  regexReplaceAll "\\W+" $domain "-" | nospace }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $noDotsDomain }}
spec:
  secretName: {{ $noDotsDomain }}-tls
  issuerRef:
    name: letsencrypt
    kind: Issuer
  privateKey:
    rotationPolicy: Always
    algorithm: ECDSA
  dnsNames:
    - "{{ $domain }}"
    - "*.{{ $domain }}"
{{- end }}
