{{- range $domain := .Values.domains }}
{{- $noDotsDomain :=  regexReplaceAll "\\W+" $domain.name "-" | nospace }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $noDotsDomain }}
spec:
  secretName: {{ $noDotsDomain }}-tls
  issuerRef:
    name: {{ $domain.issuer | default "letsencrypt-tlsserver" }}
    kind: Issuer
  privateKey:
    rotationPolicy: Always
    algorithm: ECDSA
  dnsNames:
    - "{{ $domain.name }}"
    - "*.{{ $domain.name }}"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-tls-{{ $noDotsDomain }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`fake`)
      kind: Rule
      services:
        - name: noop@internal
          kind: TraefikService
  tls:
    secretName: {{ $noDotsDomain }}-tls
    domains:
      - main: "{{ $domain.name }}"
      - sans: ["*.{{ $domain.name }}"]
{{- end }}
