---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oscarr-nl
spec:
  secretName: oscarr-nl-tls
  issuerRef:
    name: letsencrypt
    kind: Issuer
  privateKey:
    rotationPolicy: Always
    algorithm: ECDSA
  dnsNames:
    - "oscarr.nl"
    - "*.oscarr.nl"
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-tls-oscarr-nl
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`fake`)
      kind: Rule
      services:
        - name: noop@internal
          kind: TraefikService
  tls:
    secretName: oscarr-nl-tls
    domains:
      - main: "oscarr.nl"
      - sans: ["*.oscarr.nl"]
