---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: factorio-admin
rules:
  # kubectl delete pod
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - delete
  # kubectl port-forward
  # kubectl exec
  - apiGroups:
      - ""
    resources:
      - "pods/attach"
      - "pods/exec"
      - "pods/portforward"
    verbs:
      - create
  # kubectl debug
  - apiGroups:
      - ""
    resources:
      - "pods/ephemeralcontainers"
    verbs:
      - patch
      - update
  # kubectl rollout restart
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - statefulsets
    verbs:
      - patch
  - apiGroups:
      - "*"
    resources:
      - "alertmanagerconfigs"
      - "configmaps"
      - "controllerrevisions"
      - "cronjobs"
      - "csistoragecapacities"
      - "daemonsets"
      - "deployments"
      - "endpoints"
      - "endpointslices"
      - "events"
      - "events"
      - "horizontalpodautoscale"
      - "ingresses"
      - "ingressroutes"
      - "ingressroutetcps"
      - "ingressrouteudps"
      - "jobs"
      - "leases"
      - "limitranges"
      - "middlewares"
      - "middlewaretcps"
      - "networkpolicies"
      - "persistentvolumeclaims"
      - "poddisruptionbudgets"
      - "podmonitors"
      - "pods"
      - "pods/log"
      - "podtemplates"
      - "probes"
      - "prometheusrules"
      - "replicasets"
      - "replicationcontrollers"
      - "resourcequotas"
      - "rolebindings"
      - "roles"
      - "sealedsecrets"
      - "secrets"
      - "serverstransports"
      - "serviceaccounts"
      - "servicemonitors"
      - "services"
      - "statefulsets"
      - "thanosrulers"
      - "tlsoptions"
      - "traefikservices"
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: factorio-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: factorio-admin
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: "https://auth.oscarr.nl#oscrx"
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: "https://auth.oscarr.nl#rboortman"
