---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    a8r.io/description: Expires on Thu, Aug 5 2027. https://github.com/settings/tokens?type=beta
  name: github-token
  namespace: drinkn-hooks
spec:
  encryptedData:
    token: AgB6I1LC0vnajCQo9B3aZOL+Dy/rSE33isTlmaWbFYwGuCPRRwAS6ijTx6mCM7FrguGFxjzJ6ZGtk5OcX1RVdTtSpeTNDpa541nzBI7n/JEotCy6MuvMcyZGP5Yjjs4qPbLphEey3p7geY4Rp/9Ohr1daaWJWIQn6Y5ZbJWeHl2jPriXWQN455ESRYN4Ha4VrHNcLnOpr7KfThg02lZjnChncRElaKnMKMi05R6QViY/1D9UggHHuprqvTcL/trKLtlB+/lskkIyU57J3JKl8XFMSfuk+m26uwlHSBxUJQfzktDP7mhWx3W80IdN9Dlb5YSFKKfWePE7LJE8s1R8mlMGtFXM3p3dkZB7Nwp6vtPIQVI982FeLvS+Nabfr7rEBBZ1hQIIeTnggcmVBDXuaDFAfsOpaqymvHUgGvtLuG2IsCBxUwSv9MzryARwlwljB5dBKdMH7Zh9YPSxFBlAPw3+sM0bxO5Dvc6Hk/pENNqAMw2+y3JJgdY8yX2lP92eSph3FZG1aY3WyZTOxnmrfAdYC2RkR1g8RNC1r6FZJMPr2qHClH7epPi7Ss9NaQ4uSFX0s2KL1L4EURsSZPfOOZb1q5l7RAeyQrvuEv1+nAeI7lNDQqQ3eniI2eaI8KDxeEMF0iZodRfWeky7rU7kkSl9eMvI+inHoYCz3N0lO8Slb8NaHSqM/IwzqhLnbNiaq5c8jeJKmfQ5zaj9gmRdLByO0emVUGl0esjnpYWEj7kis9xgl7bAgrb7iwTq2G91Z/sbxyhQn8HR2C5w/LyTn1tEUSKs4gazzo0P3EoFENw5tH8gngRwDmZ5VlEINQ8=
