---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    a8r.io/description: Expires on Sun, Jul 12 2026. https://github.com/settings/tokens?type=beta
  name: github-token
spec:
  encryptedData:
    token: AgBVVWZ6v4+RxxmGk111EXqkThffN0WF5K7sUlTcBtYMLlJBooIUMQcvieXOVvblpdYR3DSwhle8mR8Z5OmRREKAMS/7x7NEUvByYDcvbv6Np/9qFFTUKYQEKsTMeeWhrMVssJL52dfxINnbksKZ/PrNyKQW4zAugZ2uMPRPG6lxdmRQJ5FAA0yb7Bi6AhIcV7bSUgO76wvvd9JOMFYa42mP6RUzX8nLSXo+Uhz5awOwJIVyucCgXu7cPMyiaX8zZQrIkIjTqIQcBPuHSW1OlfgsD4u4sxB0oYYe8+0D2GyaC1ItcI0ydw4BpCcl4H2ilcTp5/M172QwoJH2F9FLLema07owahobt58rB7bTqkWHGNwerhfs9kvaUZ1cXorAKOixfw18CL8OkDYlXJ31SHNi5W5FFYA8DwJxriUcC6XNm3OSNe8aEVPsfscp+Bslud1Veuwj1Jg1R7z2NLsq5jqjkXgWhqpaQaljnrF+V9YD/zD6wvhDpkyqsMt9h7T3JkrQxAZ5/UUTd3NhvKopJ7hAfxv4FhVhZGeRDiGsN6hCP94demcfElj+5hImHAVwiYydbzf0Llotoh+6ZIVa31tWBgG091Y+Y13EVqoyJlaswHfWyB3/xv4MpsV7F0TTL0CVBFAlF+fcOz13ifd9OiirTU4SQWDMRE7yFY3OXnqHi/Ey9Q7LV2/PxDGCUJYgm4HElm8MPJbqtOW+mx3gMeA+wOHkYaHlYgTlnF/qJ6d5yVUQHnu8FtangrLKEOcJWeVxEBRPNjBAQxKsBUzMisduiDyfHt7LivvVAXMtDYXlQ3FZ6a0Q6SReahfBYH8=
