---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dex
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dex
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd-managed/dex
    repoURL: https://github.com/bierteam/uber-kubernetes.git
    targetRevision: HEAD

syncPolicy:
  syncOptions:
    - CreateNamespace=true
  managedNamespaceMetadata:
    labels:
      pod-security.kubernetes.io/enforce: baseline
