---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dns-updater
spec:
  schedule: 0/5 * * * *
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          nodeSelector:
            dualstack: "true"
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
          containers:
            - image: ghcr.io/bierteam/kubernetes-dns:0.1.0@sha256:b176f93e420e298bd0cd52e48bed1260c2988b693fe5d0aa80bd0dd05937a0e7
              securityContext:
                seccompProfile:
                  type: RuntimeDefault
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                runAsNonRoot: true
                runAsUser: 1000
              imagePullPolicy: IfNotPresent
              name: dns-updater
              envFrom:
                - secretRef:
                    name: dns-updater-env
                    optional: false
