---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dns-updater-env
  namespace: dns-updater
spec:
  encryptedData:
    CLOUDFLARE_API_TOKEN: AgBUu3AK83cxMH4TEePD87faS/e8fDf6yScJkBBpNwWT5rwjdPOJ13ZrfZILgfzvnC1VUS49yfsVf1TEncE4rRG8x2oBI1jswqTx44zjmGIzs59wJS9ss1JLRtTUTRPAHXGdkWAtKevxM67Kq9Li/l4q4qwEKrdw74QGfiaNhFHyR9z2VQ2eJjO+vD6ZDjD6tHTh9kACiKhRrUGGsbaajVM+B/5TaO9xWuaIUmKYgaqM9C37zc/aRtSXjd5MqrYQ2BcFu01amnL9B4VdJQbcgK0+60CY9TfeIkJwK85P48kxe/IDo+GuHD+gOQ/k2Di4W/Gfqo8aJsKUdSCNtmfsIIoZgSTqbmrdDkwjhC3iavYHeCId1MBYrLW4J1rH/5abBu2l/02GiTxIfn3ddf52LUk78SfeszDeBpqzAYgEppx3ElOvTdbDjzf+XM/1xSzILdkdPUGE6W0fRSQdaXS4QBJXItmJl9oxEUGWDYefrw8V6UDqVUNWSNfA1zXp3/vl5Z6Qd/GZFT5vPFN6aSLted+ZJTIXpbBF+LPFVRPgg3ZR3MEpK2GFquNMajix7G8Yfa8RS8a+ZMpn8qw4d2LPhK4X3hQClSG30HwnBZT+qUYCL381PUIjRJCzHDqCUk3Du0Qvo9fw6o2wKJ6ie6iOOPZaHj6FZtnExGNpnCPR1BaBuBJ+JTZQ8NbwyFUXf0wWQoGbJ2gCptCFRM0BqrdbgC8cDm6Mx4qAaFK6yHOOr4TbrSy8yzSYzcnX
