apiVersion: v2
name: cert-manager-wrapper
type: application
version: 1.0.0
dependencies:
  - name: cert-manager
    version: v1.21.1
    repository: https://charts.jetstack.io
  - name: cert-manager-webhook-pdns
    version: 3.2.5
    repository: https://zachomedia.github.io/cert-manager-webhook-pdns
  - name: tlsa-dnsendpoint-controller
    version: 0.2.2
    repository: oci://ghcr.io/oscrx/charts
