domains:
  - name: 0scar.nl
    issuer: letsencrypt-servfail
  - name: bruinsma.it
  - name: devopscar.nl
  - name: doktermarjolein.nl
  - name: lab.oscarr.nl
  - name: ninoo.nl
  - name: oscarr.nl
  - name: oscarrr.nl
    issuer: letsencrypt-servfail
  - name: vdbrom.com

ips:
  - address: 185.132.110.37
  - address: 2a05:f080:0:3800:be24:11ff:fee2:7e61

issuers:
  # Profile defaults to shortlived in templates/issuers.yaml, set `profile:` to
  # override: https://letsencrypt.org/docs/profiles/
  - name: letsencrypt
    cloudflare: true
  - name: letsencrypt-servfail
    servfail: true
  - name: letsencrypt-http01
    http01: true
  # https://letsencrypt.org/docs/staging-environment/
  # - name: letsencrypt-staging
  #   server: https://acme-staging-v02.api.letsencrypt.org/directory
  #   cloudflare: true
  #   account_key: letsencrypt-staging
  # - name: letsencrypt-staging-http01
  #   server: https://acme-staging-v02.api.letsencrypt.org/directory
  #   http01: true
  #   account_key: letsencrypt-staging

# https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml
cert-manager: # set values for wrapper/umbrella chart
  installCRDs: true
  featureGates: ACMEUseARI=true
  enableCertificateOwnerRef: true

# https://github.com/oscrx/tlsa-dnsendpoint-controller
tlsa-dnsendpoint-controller: {}
