---
# This has a chicken and egg problem yet to be resolved
# Sealed secrets will need te be installed and the private keys restored from backup
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    oidc.dex.clientSecret: AgBPZmlzrXgiKOf1C0OjwSImLnMMvhe9TWJiIsP3uMkRpOftRLg55mQyX9cTjclUTkciW/ewMLqRA7A2PzayRH9fHrPb9hecfAgY+ikVklHSbB6G1KVTMgbh+MOMfmkUHYy8/wvhodjt7q7GrW4WBG8yMJpc2Tl2lmksLTInyo4EAGUU97PtcO/Ape8OReoaflSEgm4L5nFzEPq9iiHIUbBJ2u+F8eloA6VK3fAU1n2io43D5I58OfD6rQiWuhDG7t83+WLwH6uVb4gTtX0eMH7tvQrPNp0fzXLLoQkMF9nIPUb9cUBf82ok6ha4Kb5gAxhT8CgzLT/t3VU/G1l3nV9afdM+tvL6huy2nSBujkIg8fz8dyxRDJBQLj0kzy+ND69ufxQk6rtraEc5caRisGdbUh8lV69smP5uufLdISwf7jXkL71GSY1nPe/DzrdER+PWJtvmYgilLMDGH4QhLddKyetS07d20inNmIx71h42d/dkymum6n0uYM1xeBeCk7r4VYP0USkGS6WsRmaQbS+07wHbqDcwfkV2DqHoOwESZUTCLb3spWwBfX+dAbf27UEmuGiFU8CnLVV+z7JaM3lut4sKEayBAqkk96u3Qf1Li1lVyTPiEueT+CeQsWhz4BFB+yAakQADus6NaSxnyYGqGij97vQ20kiZxEQYZEDeKkynEEjiougzhnhtn6nIvtXrVDqoSPW6bo9RWse4onzKiiNd0JzzHfg5ZSnC0zIDN6suq6RCGdBK
