---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
  annotations:
    helm.sh/resource-policy: keep
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
  sourceRepos:
    - https://github.com/bierteam/uber-kubernetes.git
    - https://github.com/bierteam/drinkn.git
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: restricted
  namespace: argocd
spec:
  destinations:
    - name: in-cluster
      namespace: drinkn-pr-*
    - name: in-cluster
      namespace: drinkn-hooks
  clusterResourceBlacklist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
  sourceRepos:
    - https://github.com/bierteam/drinkn.git
