---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gim-tracker
  namespace: gim-tracker
spec:
  encryptedData:
    backend-secret: AgDRdzUr6zCzzuSF/SldJQFtxauAZUuJBBgyjl3NCRU/LQHIigFBABIXYDKcmbtAzyOgC3s2dmY0V5lG6IQf3MWzBDH0Pyc0F7KUVj2D/DxpTd6P+7cN2NjYzMZEp8+AtPyJDsQKKj/192GudFW9dP5yB/lWxDYHIhlk5UoSVTFCmb0uD3OFRC0SuSlq7lS+1iRcnhM0ZmcpNp3lguET/AzopEWlHnFxl/KAvT6npBi8lT85I73S71W+eL8GGJml6dzq+72SrLhjumzrNtXabc6dEeyiMOB0Tcqchz/B4UQUdQUvlgCHxfVqfAybG7ctNmqslyHekC+QVH6sSRmNdq4s6s1gNmE2ApJc5DfU3bKyPoUrHl5qopgHPoh5Gpjwg2dUop3MF/vYw3e7eThw4JgdLzX8VaPwXQEEHLG9SlXZoONpgup0ysuijNxVaXKIxoZsFAGxPUobkDzCG/SAfQnOqM5BiWwVg+Emofl2AUfTgzDBDjMjabRkkys2+HkAPY27cZX/hgQV2Jtii0K17xatCPvqkoaewgwXqAlQvtkuISvKW+2KAZctTbWpKNzgvpQBeIHSTb3FxCrXtQ4A1j+nxMV6DN8H2x48AOedbN0Or0x7LucvKepKe64xzIhFPqpcJI9fwTgzJU4i+oaR6UNxYHn5AbrdfoMDPH/Jr7klyWDWR+XSRu0gpgv/YSSDL0Hs6Mln6PKZi4hfyibvlWElOa8OX5S6jE7nAJZaK5s=
# echo -n <BACKEND_SECRET> | kubeseal --raw --name gim-tracker --namespace gim-tracker --controller-name sealed-secrets --controller-namespace kube-system
