---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: local-path-provisioner
provisioning:
  diskSelector:
    match: system_disk
  minSize: 20GiB
encryption:
  provider: luks2
  keys:
    - tpm: {}
      slot: 0
