---
# https://docs.siderolabs.com/talos/v1.14/reference/configuration/kubernetes/kubeauthenticationconfig
apiVersion: v1alpha1
kind: KubeAuthenticationConfig
configuration:
  anonymous:
    enabled: true
    conditions:
      - path: /livez
      - path: /readyz
  jwt:
    - issuer:
        url: https://auth.oscarr.nl
        audiences:
          - kubernetes
      claimMappings:
        username:
          claim: preferred_username
          prefix: "https://auth.oscarr.nl#"
        groups:
          claim: groups
          prefix: ""
