---
# https://docs.siderolabs.com/talos/v1.14/configure-your-talos-cluster/storage-and-disk-management/swap
apiVersion: v1alpha1
kind: SwapVolumeConfig
name: swap
provisioning:
  diskSelector:
    match: 'system_disk'
  minSize: 4GiB
  maxSize: 12GiB
encryption:
  provider: luks2
  keys:
    - slot: 0
      tpm: {}
---
# https://docs.siderolabs.com/talos/v1.14/configure-your-talos-cluster/storage-and-disk-management/swap#zswap
apiVersion: v1alpha1
kind: ZswapConfig
maxPoolPercent: 25
shrinkerEnabled: true
---
# https://docs.siderolabs.com/talos/v1.14/configure-your-talos-cluster/storage-and-disk-management/swap#swap-tuning
apiVersion: v1alpha1
kind: KubeletConfig
config:
  memorySwap:
    swapBehavior: LimitedSwap
---
apiVersion: v1alpha1
kind: SysctlConfig
params:
  vm.swappiness: "130"
  vm.page-cluster: "0"
