# https://external-secrets.io/latest/provider/github
# kubectl create secret generic github-app-private-key -n external-secrets --from-file=key=private-key.pem 
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: github
spec:
  provider:
    github:
      appID: 1263679
      installationID: 66524638
      organization: bierteam
      repository: uber-kubernetes
      auth:
        privateKey:
          name: github-app-private-key
          namespace: external-secrets
          key: key
