# https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml
argo-cd: # set values for wrapper/umbrella chart
  global:
    revisionHistoryLimit: 0
  configs:
    cm:
      application.instanceLabelKey: app.kubernetes.io/instance
      url: https://argocd.lab.oscarr.nl
      oidc.config: |
        name: dex
        issuer: https://auth.oscarr.nl
        clientID: argocd
        clientSecret: $oidc.dex.clientSecret
        cliClientID: argocd-cli
      admin.enabled: "false"
      users.anonymous.enabled: "true"
      server.rbac.log.enforce.enable: "true"
      statusbadge.enabled: "true"
      resource.exclusions: |
        - apiGroups:
            - cilium.io
          kinds:
            - CiliumIdentity
          clusters:
            - "*"
        - apiGroups:
            - velero.io
          kinds:
            - Backup
          clusters:
            - "*"
    params:
      # https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#traefik-v22
      server.insecure: true
    rbac:
      policy.csv: |
        p, role:anonymous, applicationsets, get, *, allow
        p, role:anonymous, applications, get, *, allow
        p, role:anonymous, logs, *, *, deny

        g, oscrx, role:admin
        g, bierteam, role:admin
      policy.default: role:anonymous
      scopes: '[groups, preferred_username]'
    secret:
      createSecret: false # handled by sealed secret
