# https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml
argo-cd: # set values for wrapper/umbrella chart
  global:
    revisionHistoryLimit: 0
    image:
      repository: quay.io/argoproj/argocd
      tag: v3.1.9
  controller:
    dynamicClusterDistribution: true
  configs:
    cm:
      url: https://argocd.lab.oscarr.nl
      oidc.config: |
        name: dex
        issuer: https://auth.oscarr.nl
        clientID: argocd
        clientSecret: $oidc.dex.clientSecret
        cliClientID: argocd-cli
      admin.enabled: "false"
      users.anonymous.enabled: "true"
      server.rbac.log.enforce.enable: "true"
      statusbadge.url: https://argocd.lab.oscarr.nl/
      statusbadge.enabled: "true"
      resource.exclusions: |
        - apiGroups:
            - velero.io
          kinds:
            - Backup
          clusters:
            - "*"
    params:
      # https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#traefik-v22
      server.insecure: true
    rbac:
      policy.csv: |
        p, role:anonymous, applications, get, *, allow

        g, bierteam, role:admin
        g, oscrx, role:admin
        g, NvdLaan, role:admin
        g, PeterOosterom, role:admin
        g, xm0ur3r, role:admin

      policy.default: role:anonymous
      scopes: '[groups, preferred_username]'
    secret:
      createSecret: false # handled by sealed secret
