# https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/values.yaml
cilium: # set values for wrapper/umbrella chart
  cluster:
    id: 0
    name: ubernerds
  hubble:
    enabled: false
  ipv4:
    enabled: true
  ipv6:
    enabled: true
  kubeProxyReplacement: true
  k8sServiceHost: localhost
  k8sServicePort: 6000
  hostPort:
    enabled: true
