# Wrapper-chart values, consumed by templates/loadbalancer.yaml.
loadBalancer:
  enabled: true
  pool:
    blocks:
      - "2a05:f080:0:3800:1b::/112"
  l2:
    interfaces:
      - "^en.+"

# https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/values.yaml
cilium: # set values for wrapper/umbrella chart
  ipv4:
    enabled: false
  ipv6:
    enabled: true
  kubeProxyReplacement: true
  k8sServiceHost: localhost
  k8sServicePort: 7445
  l2announcements:
    enabled: true
  k8sClientRateLimit:
    qps: 50
    burst: 100
  ipam:
    mode: kubernetes
  securityContext:
    capabilities:
      ciliumAgent:
        - CHOWN
        - KILL
        - NET_ADMIN
        - NET_RAW
        - IPC_LOCK
        - SYS_ADMIN
        - SYS_RESOURCE
        - DAC_OVERRIDE
        - FOWNER
        - SETGID
        - SETUID
      cleanCiliumState:
        - NET_ADMIN
        - SYS_ADMIN
        - SYS_RESOURCE
  cgroup:
    autoMount:
      enabled: false
    hostRoot: /sys/fs/cgroup