---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd-managed/cilium
    repoURL: https://github.com/bierteam/uber-kubernetes.git
    targetRevision: HEAD

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    # https://github.com/argoproj/argo-cd/pull/10672
    # coming in argocd 2.6 (2023-1-9)
    # managedNamespaceMetadata:
    #   labels:
    #     pod-security.kubernetes.io/enforce: baseline
    # automated:
    #   prune: true
    #   selfHeal: true
