---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drinkn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: drinkn
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd-managed/drinkn
    repoURL: https://github.com/bierteam/uber-kubernetes.git
    targetRevision: HEAD

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: baseline
    automated:
      prune: true
      selfHeal: true
