---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: rook-ceph
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd-managed/rook/operator
    repoURL: https://github.com/bierteam/uber-kubernetes.git
    targetRevision: HEAD

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: baseline
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-cluster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: rook-ceph
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd-managed/rook/cluster
    repoURL: https://github.com/bierteam/uber-kubernetes.git
    targetRevision: HEAD

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: baseline
    automated:
      prune: true
      selfHeal: true
