---
argocdApps:
  # - name: string (mandatory)
  #   folder: string (optional)
  #   namespace: string (optional)
  #   podSecurity: privileged/baseline/restricted (optional)
  #   repository: string (optional)
  #   autosync: bool (optional)
  #   finalizer: bool (optional)
  - name: cert-manager
  # - name: cilium
  #   namespace: kube-system
  #   podSecurity: privileged
  - name: cyberchef
  - name: dex
  # - name: dns-updater
  #   podSecurity: restricted
  - name: drinkn
    folder: charts/drinkn
    repository: drinkn
  - name: external-secrets
  # - name: factorio
  - name: fixitloop
  # - name: friend-tracker
  - name: kubeseal-webgui
  # - name: metrics-server
  - name: misc
  - name: rick
  # - name: rook-cluster
  #   folder: argocd-managed/rook/cluster
  #   namespace: rook-ceph
  #   podSecurity: privileged
  # - name: rook-operator
  #   folder: argocd-managed/rook/operator
  #   namespace: rook-ceph
  #   podSecurity: privileged
  - name: sealed-secrets
    namespace: kube-system
    podSecurity: privileged
  - name: traefik
    # podSecurity: privileged
  - name: unifi
  - name: oscarr
  - name: proxy-oscarr
    folder: argocd-managed/oauth2-proxy
    valuesFile: values-oscarr.yaml
  - name: proxy-bruinsma
    folder: argocd-managed/oauth2-proxy
    valuesFile: values-bruinsma.yaml
  # - name: valheim
  - name: velero
    podSecurity: privileged
