argocdApps:
  # - name: string (mandatory)
  #   namespace: string (optional)
  #   podSecurity: privileged/baseline/restricted
  #   folder: string (optional)
  #   autosync: bool (optional)
  #   finalizer: bool (optional)
  - name: cert-manager
  - name: cilium
    namespace: kube-system
    podSecurity: privileged
  - name: cyberchef
  - name: dex
  - name: dns-updater
  - name: drinkn
  - name: fixitloop
  - name: friend-tracker
  - name: metrics-server
  - name: misc
  - name: ninoo
  - name: rook-cluster
    folder: rook/cluster
    namespace: rook-ceph
    podSecurity: privileged
  - name: rook-operator
    folder: rook/operator
    namespace: rook-ceph
    podSecurity: privileged
  - name: sealed-secrets
    namespace: kube-system
    podSecurity: privileged
  - name: traefik
    podSecurity: privileged
  - name: unifi
  - name: valheim
  - name: oscarr
  - name: proxy-oscarr
    folder: oauth2-proxy
    valuesFile: values-oscarr.yaml
  - name: proxy-bruinsma
    folder: oauth2-proxy
    valuesFile: values-bruinsma.yaml
  - name: velero
<<<<<<< HEAD
    podSecurity: privileged
=======
  - name: prometheus
>>>>>>> 92481ea (Add prometheus stack)
