# https://github.com/dexidp/helm-charts/blob/master/charts/dex/values.yaml
dex: # set values for wrapper/umbrella chart
  replicaCount: 2
  revisionHistoryLimit: 0

  envFrom:
    - secretRef:
        name: dex-secrets

  config:
    issuer: https://auth.oscarr.nl
    storage:
      type: kubernetes
      config:
        inCluster: true

    oauth2:
      skipApprovalScreen: true

    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: $GITHUB_CLIENT_ID
          clientSecret: $GITHUB_CLIENT_SECRET
          redirectURI: https://auth.oscarr.nl/callback
          orgs:
            - name: bierteam
      # - type: gitlab
      #   id: gitlab
      #   name: Techforce1 GitLab
      #   config:
      #     clientID: $GITLAB_APPLICATION_ID
      #     clientSecret: $GITLAB_CLIENT_SECRET
      #     redirectURI: https://auth.oscarr.nl/callback
      #     groups:
      #       - techforce1

    staticClients:
      - id: proxmox
        name: Proxmox
        secretEnv: PROXMOX_CLIENT_SECRET
        redirectURIs:
          - "https://proxmox.oscarr.nl:8006"
          - "https://proxmox.oscarr.nl"

          - "https://pve02.oscarr.nl:8006"
          - "https://pve02.oscarr.nl"

          - "https://pve03.oscarr.nl:8006"
          - "https://pve03.oscarr.nl"

          - "https://pve05.oscarr.nl:8006"
          - "https://pve05.oscarr.nl"

      - id: kubernetes
        name: Kubernetes
        public: true

      - id: argocd
        name: ArgoCD
        secretEnv: ARGOCD_CLIENT_SECRET
        redirectURIs:
          - https://argocd.lab.oscarr.nl/auth/callback

      - id: argocd-cli
        name: ArgoCD CLI
        public: true
        redirectURIs:
          - http://localhost:8085/auth/callback

      - id: headscale
        name: Headscale
        secretEnv: HEADSCALE_CLIENT_SECRET
        redirectURIs:
          - https://headscale.oscarr.nl:443/oidc/callback

      - id: proxy-oscarr
        name: Oauth2 Proxy oscarr.nl
        secretEnv: PROXY_OSCARR_CLIENT_SECRET
        redirectURIs:
          - https://proxy.lab.oscarr.nl/oauth2/callback

      - id: proxy-bruinsma
        name: Oauth2 Proxy bruinsma.it
        secretEnv: PROXY_BRUINSMA_CLIENT_SECRET
        redirectURIs:
          - https://login.bruinsma.it/oauth2/callback

      - id: rancher
        name: Rancher
        secretEnv: RANCHER_CLIENT_SECRET
        redirectURIs:
          - https://rancher.lab.oscarr.nl/verify-auth
