#!/usr/bin/env bash
# Regenerate argocd-managed/README.md from the app list in
# argocd-managed/argocd-apps/values.yaml.
#
# The hand-maintained table drifted badly: it still listed Rook, Velero and a
# DNS updater that were removed, while minecraft, nfs-csi, cnpg and a dozen
# others never got added. It also linked two apps to the wrong application
# (proxy-bruinsma pointed at oscarr) and one to a typo'd name (treafik). All of
# that is derivable from values.yaml, so deriving it is the fix.
#
# Everything except the docs link comes from values.yaml. The docs link is an
# optional per-app `docs:` key there -- it is curated, not guessed, so an app
# without one simply gets a blank cell.
#
# Usage:  hack/gen-argocd-readme.sh [--check | --check-links]
#
# --check exits non-zero if the file on disk differs from what would be
# generated, so CI can catch a stale README instead of trusting people to rerun.
#
# --check-links requests every docs URL and fails on anything that is not 2xx.
# Kept separate from --check so generating stays offline and fast; a link that
# rots upstream is not a reason to block a commit that never touched it.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
values="${repo_root}/argocd-managed/argocd-apps/values.yaml"
readme="${repo_root}/argocd-managed/README.md"
argocd_url="https://argocd.lab.oscarr.nl"

command -v yq >/dev/null || { echo "yq is required" >&2; exit 1; }

generate() {
  cat <<EOF
# ArgoCD App state

<!-- Generated by hack/gen-argocd-readme.sh -- do not edit by hand. -->
<!-- Source of truth: argocd-managed/argocd-apps/values.yaml -->

| Name | Status | Cluster | Namespace | Docs |
| ---- | ------ | ------- | --------- | ---- |
EOF

  yq eval -r '
    .argocdApps[]
    | [.name, (.server // "in-cluster"), (.namespace // .name), (.docs // "")]
    | @tsv
  ' "$values" | sort -f | while IFS=$'\t' read -r name server namespace docs; do
    badge="[![App Status](${argocd_url}/api/badge?name=${name}&revision=true)](${argocd_url}/applications/${name})"
    link=""
    [ -n "$docs" ] && link="[Upstream](${docs})"
    printf '| %s | %s | %s | %s | %s |\n' \
      "$name" "$badge" "$server" "$namespace" "$link"
  done
}

check_links() {
  local failed=0 name url code
  while IFS=$'\t' read -r name url; do
    # --max-time so one hanging host cannot stall the whole run; -L because
    # several of these redirect (docs sites to /latest/, GitHub to a canonical
    # case). Only the final status matters.
    code=$(curl -sL -o /dev/null -w '%{http_code}' --max-time 15 "$url" || echo "000")
    case "$code" in
      2*) printf '  ok    %-22s %s\n' "$name" "$url" ;;
      *)  printf '  FAIL  %-22s %s (HTTP %s)\n' "$name" "$url" "$code"; failed=1 ;;
    esac
  done < <(yq eval -r '.argocdApps[] | select(.docs) | [.name, .docs] | @tsv' "$values")

  if [ "$failed" -ne 0 ]; then
    echo "one or more docs links are dead; fix or drop them in ${values}" >&2
    return 1
  fi
  echo "all docs links resolve"
}

if [ "${1:-}" = "--check-links" ]; then
  check_links
  exit $?
fi

if [ "${1:-}" = "--check" ]; then
  if ! diff -q <(generate) "$readme" >/dev/null 2>&1; then
    echo "argocd-managed/README.md is out of date; run hack/gen-argocd-readme.sh" >&2
    diff <(generate) "$readme" || true
    exit 1
  fi
  echo "argocd-managed/README.md is up to date"
  exit 0
fi

generate > "$readme"
echo "wrote ${readme}"
