apiVersion: v2
name: prometheus-wrapper
type: application
version: 1.0.0
dependencies:
  - name: prometheus-stack
    version: 48.1.1
    repository: "https://prometheus-community.github.io/helm-charts"
