---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
data:
  url: https://argocd.lab.oscarr.nl
  oidc.config: |
    name: dex
    issuer: https://auth.oscarr.nl
    clientID: argocd
    clientSecret: $oidc.dex.clientSecret
    requestedScopes: ["openid", "profile", "email", "groups"]
    requestedIDTokenClaims: {"groups": {"essential": true}}
  admin.enabled: "false"
  statusBadgeEnabled: "true"
  resource.exclusions: |
    - apiGroups:
        - cilium.io
      kinds:
        - CiliumIdentity
      clusters:
        - "*"
