---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`grafana.ninoo.nl`)
      kind: Rule
      services:
        - name: prometheus-operator-stack-grafana
          port: 80
