{{- range $application := .Values.argocdApps }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $application.name }}
  namespace: argocd
  {{- if ne "false" ($application.finalizer | toString) }}
  {{- include "finalizers" . | indent 2 }}
  {{- end }}
spec:
  destination:
    namespace: {{ $application.namespace | default $application.name }}
    server: https://kubernetes.default.svc
  project: default
  source:
    path: {{ default (print "argocd-managed/" $application.name) $application.folder }}
    repoURL: https://github.com/bierteam/{{ $application.repository | default "uber-kubernetes" }}.git
    targetRevision: HEAD
    {{- if $application.valuesFile }}
    helm:
      valueFiles:
        - {{ $application.valuesFile | toString }}
        # - "values-test.yaml"
    {{- end }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: {{ $application.podSecurity | default "baseline" | toString }}
        {{- if ne $application.podSecurity "privileged" }}
        pod-security.kubernetes.io/audit: restricted
        pod-security.kubernetes.io/warn: restricted
        {{- end }}
    {{- if ne "false" ($application.autosync | toString) }}
    {{- include "autosync" . | indent 4 }}
    {{- end }}
{{- end }}

{{- define "finalizers" }}
finalizers:
  - resources-finalizer.argocd.argoproj.io
{{- end }}

{{- define "autosync" }}
automated:
  prune: true
  selfHeal: true
{{- end }}
