---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: unifi
  name: unifi
spec:
  storageClassName: ceph-filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
