---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: unifi
  name: unifi
spec:
  replicas: 1
  serviceName: unifi
  selector:
    matchLabels:
      app: unifi
  template:
    metadata:
      labels:
        app: unifi
    spec:
      containers:
        - env:
            - name: MEM_LIMIT
              value: 1024M
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
          image: "linuxserver/unifi-controller:7.3.83"
          name: unifi
          ports:
            # - containerPort: 3478
              # protocol: UDP
            # - containerPort: 10001
              # protocol: UDP
            # - containerPort: 8080
            # - containerPort: 8081
            - containerPort: 8443
            # - containerPort: 6789
          volumeMounts:
            - mountPath: /config
              name: unifi
      restartPolicy: Always
      volumes:
        - name: unifi
          persistentVolumeClaim:
            claimName: unifi
