apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongo-init-pass
  namespace: unifi
spec:
  encryptedData:
    password: AgBm3eyHq7DJ1S6YXqJ/uGiXxSJUGANWJ8hgQgB6R0/QIBWh+ypE8qyDzNOtgumgh6okBhcccJKFB1jwCRTfDKC1c0Ci9cpkm+IJGN5RZOC3VRX95s55KFfK5YQlE88FsnoGF6PI3Hy6d4neogVsNfbIik2OfqKhe8J47AbXNGuoPIYqbFlDlzUJw4p5lSC2UuJepwcLakHMFsAZ4t/U093xBGLFu6yuxkDTSrWEgp80CtydjmBZe4dqM4S6nzFKpw5aXBeeoiRH3lFuEmLj8PV5FeK9qnMkkMOr8bNt9i6Xa/qrFwqnA5Iqkc32DQQSXJDEcb37JJEuoS3hJYiIjMOgi5tyaU9hix5vQuavkY+iqvw+N5GraiMENMoHUu7mpDw4BN6XDT/0ZnL/NP3OvNXiCVMRsukHakEQnduhEomqWze5aP9tWuzE1Xvia49Ga/7pYKhbI0iY+VYYypVFmlO+UmGenoaAfTMF0pG+nW8XDG55xIPNyy+FqbOFKE6TcoQJl3nh6cdCIzI7kVEXWqIG8dsLo02WrvZThv0N5YJJ4+D3aJhYvTjYngm6PLyV4kR7i7Qnyf215CxP3FYupmVZftq4bqZ5W0miDizkmnSsTJwCBiKQRokJaV50JkKimc5P1a61uecpskBpPNtPlloQess44jxoeqig9WoLRcAABXU87SirP5GDKQkYPZsnfqAqaue8t+4FGiNRf6XBh1+XgqIDoiNI9/G3iKtZ
