---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: drinkn-pils-api
  name: drinkn-pils-api
spec:
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: drinkn-pils-api
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: drinkn-pils-api
    spec:
      containers:
        - image: bierteam/pils-api:v1
          envFrom:
            - secretRef:
                name: drinkn-env
                optional: false
          imagePullPolicy: Always
          name: drinkn-pils-api
---
apiVersion: v1
kind: Service
metadata:
  name: drinkn-pils-api
spec:
  selector:
    app: drinkn-pils-api
  ports:
    - port: 80
      name: default
      protocol: TCP
      targetPort: 3000
