---
apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap
data:
  index.html: |
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <style>
                #rick {
                    display: none;
                }
            </style>
            <script>
                function playRick() {
                    const rick = document.getElementById('rick'); // get element
                    rick.style.display = 'block'; // unhide video
                    rick.requestFullscreen(); // enter full screen mode
                    rick.setAttribute('src', rick.getAttribute('src') + '?autoplay=1'); // autoplay video
                }
            </script>
        </head>
        <body>
            <iframe id="rick" width="560" height="315" src="https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            <button onclick="playRick();">Klik mij!</button>
        </body>
    </html>
