---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ninoo-nl
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <!-- https://github.com/bierteam/uber-kubernetes/blob/main/argocd-managed/ninoo/rick.yaml -->
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="script.js"></script>
        <link rel="stylesheet" href="style.css">
      </head>
      <body>
        <div class="bodyContainer">
          <div id="player" allow="autoplay; fullscreen"></div>
          <button id="button" class="button" role="button">Klik mij!</button>
          <a href="https://www.linkedin.com/in/nino-van-der-laan-baa3421ab/">
            <img src="linkedin.png" class="linkedin"/>
          </a>
        </div>
      </body>
    </html>
  style.css: |
    .bodyContainer {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
    }
    #player {
      display: none;
    }
    .button {
      background-color: #ffffff;
      border: 1px solid #222222;
      border-radius: 8px;
      box-sizing: border-box;
      color: #222222;
      cursor: pointer;
      display: inline-block;
      font-family: Circular, -apple-system, BlinkMacSystemFont, Roboto,
        "Helvetica Neue", sans-serif;
      font-size: 16px;
      font-weight: 600;
      line-height: 20px;
      margin: 0;
      outline: none;
      padding: 13px 23px;
      text-align: center;
      text-decoration: none;
      touch-action: manipulation;
      transition: box-shadow 0.2s, -ms-transform 0.1s, -webkit-transform 0.1s,
        transform 0.1s;
      user-select: none;
      -webkit-user-select: none;
      width: auto;
    }
    .button:focus-visible {
      box-shadow: #222222 0 0 0 2px, rgba(255, 255, 255, 0.8) 0 0 0 4px;
      transition: box-shadow 0.2s;
    }
    .button:active {
      background-color: #f7f7f7;
      border-color: #000000;
      transform: scale(0.96);
    }
    .button:disabled {
      border-color: #dddddd;
      color: #dddddd;
      cursor: not-allowed;
      opacity: 1;
    }
    .linkedin{
      position: fixed;
      bottom: 5px;
      left: 50%;
      transform: translateX(-50%);
      width: 20px;
      height: 20px;
    }
  script.js: |
    window.onload = function () {
      function playRick () {
        const button = document.getElementById('button') // get button
        const iframe = document.getElementById('player') // get rick video
        button.style.display = 'none' // hide button
        iframe.style.display = 'block' // unhide video
        if (iframe.requestFullscreen) {
          iframe.requestFullscreen()
        }
        player.playVideo()
        player.unMute()
        player.setVolume(100)
      }
      document.getElementById('button').addEventListener('click', playRick)
    }

    var tag = document.createElement('script');

    tag.src = "https://www.youtube.com/iframe_api";
    var firstScriptTag = document.getElementsByTagName('script')[0];
    firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

    var player;
    function onYouTubeIframeAPIReady() {
      player = new YT.Player('player', {
        height: '315',
        width: '560',
        videoId: 'dQw4w9WgXcQ',
        playerVars: {
          'autoplay': 1,
          'controls': 0,
          'modestbranding': 1,
          'rel': 0,
          'showinfo': 0,
          'loop': 1,
          'disablekb': 1
        }
      });
    }

binaryData:
  linkedin.png: iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAYAAABccqhmAAAZGElEQVR42u2dfWhUZ77HJYhIkEvJH1LKIsuylFKkSJFyKUXKRYpI2T8WKaWUUoosUi41mTkz52XOvL9PxmQ00ahJjBpjYmLU3lIul1KWIqVIkVKkFJHLIiLLpRQppRQR2X2+WZtbq2bezpzfefl+4cO2XU2e5/f8vt9zzsw5z1m3jvK1pqZPPZXNFbeaVmqXbtjvxfWErcXMsUhUn1N8pP75yuBQ7OuoZtwaisRvq3++o/77PfXv938N/hv+P/wZ/Fn8Hfxd/Az8LPxM/Gz8Dvwu/E78bun5U1TgNXNydmM6U9hmmPZbsbhVVAadV6a8qrjzwf7oPyTBGDAWjAljwxgxVoxZum4U5TtNTs30J1O5HepoG1FHXRzFv1VH4/vSRm8XjBljxxwwF8wJc5OuL0V5SsP10c3qtHqPOnritP3q/kHtnrR5ewXmhjlirpgz5i5df4pyVWPjE/12MrtbHRlHlRmuKVOIG1MwEHAJcQ21QE1QG+n1oSjHVanWn1FHvH3qOvljdWr8s7TxvApqgxqhVqiZ9LpRVMcqV+pbVCNHVEN/oY50vruGlwY1Q+1QQ9RSej0pqqkajfEBw1w50l8O86l9Ly4VUFPUFjWWXmeKWtX8wmKfun7dpa5jl1Sj3pU2S9BBjVFr1By1l15/KqQqlWqb43rCikT1m9KmCCuoPdYAayHdD1RIlM4Utqsj0CyP9t7hwVnBLNZGuj+oAMq0bJzmvx7V9M+km52sDdYIa4U1k+4byuc6emxqvWml3lanmt9INzZpD6wZ1g5rKN1HlM+EpjFM+52hSPyGdCOT7sAaYi0ZBFRTTU+f7EvYmTfV0eO6dOMSx88IrmNtscbSfUZ5UOq6cadqkq+kG5X0PAi+wlpL9xvlEeUL5a1azPxEujGJu2DNsfbS/UcJabjeGNCNxOEgP31H1gZrjx5AL0j3I+WSKpUarvP3DkXi30k3IPEG6AX0BHpDuj+pHipfqOB0/3PphiPeBL2BHpHuU8phnZg5vcG0klnevUeagR5Br6BnpPuWckC5XGl7VDOuSTcW8RfoGfSOdP9SHWrh3NL6B0d9fshHOgK9gx5CL0n3M9WGCsXqH7WYcUW6gUgwQC+hp6T7mmpBdjL77uBQ7EfppiHBAj2F3pLub+oJOjR2ZJNuJGalG4UEG/SY6jVuXuol5fLl56Ian9gj7oBeQ89J9z2llErn9vCUn7gNeg69J93/odXxyek+00rl1WJwx10ixX30IHpR2g+h0mhjbFMsbl30QAMQ8g/0InpS2hehUKlc+x0f2yVeAz2J3pT2R6CVyRa24fXV0otNyONAb6JHpX0SSCVTudcGh2I/SC8yIWuBHkWvSvslUMJWTnyQh/gF9Cp6Vto3gZBppd7nu/WI30DPonel/eNrqRSNSy8kId2AHpb2kS+lG3ZKevEIcQL0srSffKW4nshKLxohToKelvaVL8QjPwkqPBNoIl7zk6DDzwSeIHxiKr04hLgBvx34jR58z8+v+kgoQK/zPoEHwl1TvMmHhA30fOjvGMxki9t4ey8JK+h9eEDahyLCk1N8sIeEHXggdE8R4tlpPtJLyL+AF0KznwB2T+FmHoQ8DDwRip2FHmzjJV5wQrwGvCHtz54Kmyh+wD38CHkS9wO70Wg+X36Ou/cSsjbwSD5oW47jpR3ct5+Q1oBXAvXyEb6xh5D2gGekfeuI8D416WIS4kd8/y5CvFE1aNf9+wc1vDv+e8XXcT3xpRYzFcbNoUicH24SR4F3fPtWYrxTPSiv6Fbm/kHXE6dS6fyeY8dPPP24+c4vLG7MFyovG2Yyq0LhW+kxk2AAD8FL0n5uW6aV9P2uPsr431mJ9ODE0cm279JSYbBTnSFclp4D8T/wkrSf21IuV9quTpXvSReuU3Car47kk6ON8ae6rUUmW3wrEtW/l54T8S/wEjwl7euWdGLm9AZ1fXxNumidoq67fkqmcm84WZPa8OiWWNy8Kj034l/gKXhL2t9N5edT/wdvdXm5F3U5dOjIJl1P/FV6jsS/eP5SQF33bvXr5h4Ytzpd/49e1gc3RMViPBMgnfcoPCbt88eqVqv3aTHzc+kidYqtTlzcqNOBkYO/j0T1O9LzJf4EHoPXpP3+iBJ2Zq90cTolrlufulmrbK74jvSciX+B16T9/pDq9cYAvjKTLkwn4BPWYqnq6mnV4tJyX1xPfCE9d+JP4DV4Ttr3q9KNxGHponSKMuI5iZqVSrVd0nMn/gWek/b9ivKF8lY/f+dfKFZekajb8oVL2BnphvT8iT+B5+A9af+v02LmJ9LF6BQtZtySrF3CThela0D8C7wnan47md0pXYRuiOvWtGT9huujO6RrQPwNPCjSvNPTJ/v8vrNvws78RTIAlpcv9Ueicd9ePhF54EF40fXmxauNpCffLdlc6VXJAIBiceumdB2Iv3H9NWNHj02tV8lzXXri3XLw4OEXPBAAgXhkmsgBL8KTrjWtYdqBuJGlWhvZIh0AumF/Jl0H4n/gSVcaFkkzFIkH4uurhjfOAL6UrgPxP/CkK2cBppV6W3qyTpHNFV/1QADckq4DCQbwZo/Nb+OT/8Bs752wM/skzX9++eIm7iVInALehEd71rB2Mvu69CSdRB19ZyQDoFobeVW6BiRYwKM9a9iopgfqA6uoZtyeOHpc7NFKK5EuS9eABAt4tCfNms4UtktPrhcUipVXJcy/uLiMZwH+Jj1/EjzgVccbVouZgXy7T1xPLEsEQLFUDdTlFPEO8KqjzVoq1Tb7dauvZqh53c/ly65+HTg7O4f9APj1H+lVT9+FZx1rWNWslvSkeok6Fb989uyCa58FZLJF3+6eRPwBPOtIs84vLOKrv8Dfr24ns4Yb5q8faDyLNw1Jz5cEG3gW3u26YZUxQrFzzb8uBUq9+wpFqXFwfEBdnwXmPgribeDdrptWNeyS9ETcAi8FUSHwWi/Mf/DQ4QF1WsYHf4hrwLvdHbEa4wNB/fBvjRC4m84UHN0nYLjeeJYvDCVuA+/Cwx03rmHa+6QnIYVhJpfGxiae7rh4SvPzi32ZbOF9dc0fqFekE/8AD3fcwFHNCPXbbfFhXcJO549MHG/rK5Wl8xfWF4qVPeqU/2vpOZBwAw93ZP5ypb4Fb8mVnoAXUEFwV50RfJhK5/dOHJ18/tKl/3rkJY1n5haeLhSrr1uJ9MFYzLwtPWZCADwML7cdALphR6QH71VUqt6Nxc1b6gh/Ixa3/lfxI8OSeBV4uZPTf765hpAAAC+3Zf5Ktf4MvheXHjghpHvgZXi6ndP/0H76T0gQgafbOf3/WHrAhBDngKdbMv/Y+ET/4FDsZ+kBE0KcA56Gt5sGgJ3M7pYeLCHEeeDtpgGgxcxR6YESQpwH3m4aAJGofk16oIQQ54G31zT/cH10M29oIS425P1Y3LquG/bHppWaSNiZlGJQnar+BXddqv+2L5nKWep/y4aZnFF/7hPceIW/Jz12PwJvw+Nrff23R3qQJLgMDsXux/XEFzB6tTayY27uXPMPpR6jM3ML/aqRX06mshrCI6oZP0nPzS/A408srErXMekBkuAR161vlVkjh8YmWr8ZpQ2dOj23MV+o/Nkw7GU8tyE9Xy8Dj691/X9VeoAS4I0qxydPbHOLRmP8zw4t5v+5NeZypf6f7Y5PHW0uF0u17nelaUOHjxx72kqk82pNv5fuKy8S1fSrjy3c5NRMv7pGuCc9QAnUUeNqm33Wlaq1A887FAC33RpzNldq+ethNa5viqWqq8b/rcbGJ55Slxpltba8p+VXwOPw+iMFS6ZyO6QHxwDwdwBgNyXVR/bZ+XMbuv+Nzqg2PPIHdSbyqXSPeQl4/ZFCxfVEaB//ZQA0V7MAwJZnlWp9m5t1bFXnz1/sU02vqYAK5Rnub4HXHymSWsA56YExAPwZAKaVujhxdHKTmzXsRLl8eQc/G1gJ67lHiqMKE9pNKxkAzfWkAFBH1tGTp2bFXrDarkrl2rNRzbgl3XOSwOsPFWXm5OxGfEcrPTAGgL8CIJ0pFN2sm1OqDY/+AW+Glu47KeB1eH61IGoht0kPigHgrwBIpXLDbtbMaRWK1a1hfkMTPL9aDMO035IeEAPAPwGQsDNzlz78yDen/U9SJlvcHdadr+D51UKoRipKD4gB4I8A0A37yxMzpzd2/xO9IdwrIN1/EsDzq0VQ10Pz0gNiAHg/ACJR/c7I6KHfu1mrXuv07NkNWswM3fsb4PnVIoT1FmAGQOvK5cu784XKu27WyS3lC+WXwnYpAM+vFgDJLj0gBoC3A+DMmfm23o7kNxmGfUq6D10OgDsrE5+aPvWU9GCkYQBQteGRLbiVWboX3QTeV9d2xa3SA5GGAUBBhpmclO5FN4H315lWapf0QKRhAFBQpVp/Pkw7YsH72AXoPemBSMMAoH6Rquln0v3oFvA+ngK0pQciDQOA+kXJVC40B0TlfQtPAYZ+GzAGAPWLjh6bHgjLY8PwPr4CDO1jwAwA6nFSdQ3FBiLwPgLgI+mBSMMAoH4t00rFpXvSpQD4CJcAV6QHIg0DgPq1iqXaS9I96Qbw/jp1vRO6+6AZAO5pfv5c3+LShaePT868MFxvvDgyemjbqVNzzy1fuOTZHYTOL1/aoI6Ogd9MFN5fF/bdURgAzurYscm+AyOHXknYmQO6YV9RY/zpcd+tK4PhU+ibViI9p464bywsLHnqCcMwnBnD++tU84d2ZxQGgHM6Mze/Ppcv71Wmvt7JXJTh/p7NFQcXF5fXS88FUuE1I92XLvT9bVwChPpBIAZA96oNj76gDOPIpST2G/DCI8emldKk+7LXwPv4FiAU33kyAHojddR/Q9XP0XfzqVPTv1eq9a2S80pn8oF/Tya8j88AQvUcNAPAOeULlTd6tZmsuiS43Tg43pN3CbaicmU48N8EwPsMAAZAR1Kn/S/1+rVbhpn8dH5hUWTvwSNHjm+R7ksGAAPAkwFwevZsv/rdN9xYm3yh/I7EHJfOX9ykzm7Ee5MBwADwXACk0vmsW2sTi5t/O798UeSbAXUZEmhvrAQAPwRkALSjyamZAdU4P7q5PoVi9Q235wlpMSPQNwOtfAjIrwEZAO0onSm4fp+8YSb/2+15Qsobgb5HZuVrQN4IxABoR7phu/4OSXWkuntmbuHf3J5r0ANg5UYg3grMAGhVRyaOi22ZVSxV/+TmXKGgB8DKrcB8GIgB0Koy2cKg1BpZiXTVzblCQQ+AlYeBwvDQAwPAGZlWaklqjdSlx/+4OVco6AGw8jgwNwRhALSqTh/0cYK4bt10c65Q0ANgZUMQbgnGAGhFFy5+uF4dMcS+MlbXq/eWzl/Y4OY6hSAA5rgpKAOgJZ2dXxS/Nfb88iVXnw0IegCsbArKbcEZAK3o0NiR7dLrdPjIsefdXKegB8DKtuB8MQgDoBUdGDm0U3qdRkbH/t3NdQp6AKy8GISvBmMAtKJK9cBu6XUabYy/4uY6BT0AVl4NxpeDMgBaUTZXYgAEjJWXg/L14AyAVsQACB4rrweHIlE91A8EMQCaiwEQLOD51Ymqf7kqPSAGAAOAAeBqAPx/z0c1Y156QAwABgADwD3g+dWJqkYqSg+IAcAAYAC4Bzy/OlHDtN+SHhADgAHAAHAPeH51oulMYZv0gBgADAAGgHvA86sTnTk5u7FX+7v7AQZAczEAggO8Ds8/NNlIVHd9qyevwABoLgZAcIDXH5msFjND+1gwA6C5GADBAV5/ZLJxPRGRHhgDgAHAAOg98Pojk02mcjukB8YAYAAwAHoPvP7IZCenZvr3D2qhfEkIA6C5GADBAB6H1x874bDeEswAaC4GQDB46Bbg30o1VCi3B2MANBcDIBjA40+csG7Ye6QHyABgADAAegc8/sQJD9dHN0u9+YUBwABgAPQWeBseX3PS6hrhmvRAGQAMAAaA88DbTSetxcxR6YEyABgADADngbebTtpOZsUXmgHAAGAAOA+83XTSY+MT/WriP0sPlgHAAGAAOAc8DW+3NPGoZnwsPWAGAAOAAeAc8HTLE9cNe5/0gBkADAAGgHPA0y1PvFKtP7N/UAvN/gAMgOZiAPgXeBmebmvy6pThC+mBMwAYAAyA7oGX2568OmUIzePBDIDmYgD4F3i57cmXK/UtYbkrkAHQXAwAfwIPw8sdFUCdOlyWngADgAHAAOgceLjjAhhmOL4NYAA0FwPAn8DDHReg0RgfUKcQd6UnwQBgADAA2gfehYe7KoIWM5ekJ8IAYAAwANoH3u26CHYyu0t6IgwABgADoH3g3a6LML+w2BeJ6jelJ8MAYAAwAFoHnoV3HSlEXE9Y0hNiADAAGACtA886VohSqbY5yB8GMgCaiwHgH+BVeNbRYmgxc1Z6YgwABoCb6+TXAIBXHS9GOlPYLj0xBgADwM118msApNL5F3tSkKimfyY9OQYAA8At+TEA4NGeFcROZl+XniADgAHglvwYAPBozwpiWja+EvxGepIMAAaAG/JbAMCb8GhPi2JaqbelJ8oAYAC4Ib8FALzZ86IcPTa1XhnmhvRkGQAMgF7LTwEAT8KbrhTGMO13pCfMAGAA9Fp+CgB40rXCIGnU9cZ16UkzABgAvZRfAgBedO3o/4sSduZN6YkzABgAvZRfAgBedLMuK5qePolvBL6SnjwDwB0xALwJPAgvulmXVdnJ7E7pAjgUAN9WayMvukW5UnfkNexazPzOrTHn8qUPpNepNjy61811UgHwnfScmwEPipj/F6km/ES6CISEEXhP1PxQvlDeun9QuyddDELCBDwH70n7f0W6kTgsXRBCwgQ8J+37VdXrjQF1He356yVCggC8Bs9J+/4hJezMXunCEBIG4DVpvz+iWq3ep8XMz6WLQ0iQgcfgNWm/P1b5QmVrkLcOI0QSeAsek/b5mjKtZFa6UIQEEXhL2t9NdWLm9IaoZlyTLhYhQQKegrek/d2ScrnSdt4bQIgzwEvwlLSv2xIvBQhxBl+c+v9WC+eW1msx44p08QjxM/AQvCTt545UKFb/ODgU+1G6iIT4EXgHHpL2cVeyk9l3pQtJiB+Bd6T964h0I3FKupiE+Al4Rtq3junQ2JH+qBa87cQJ6QXwCjwj7VtHlc+Xn+PnAYSsDTwCr0j7tSdKpXPYCee+dJEJ8Sj34RFpn/ZUppXKe6DQhHgOeEPanz3X8cnpvljcuihdbEK8BDwBb0j70xWNNsY2BWVHYUK6BV6AJ6R96apK5drvhiJxz2+7TEgvgQfgBWk/iiiTLW4bHIr9IL0IhEiA3ocHpH0oqmQq9xo3ESFhAz2P3pf2nyeEVxupgvDrQRIK0Osir/Pyskwr9b70whDiBuh1ab95UioV49KLQ0gvQY9L+8zT0g07Jb1IhPQC9La0v3yhuJ7gbkIkUKCnpX3lK/FMgAQFHvk7FD8TIH6H1/xdCp+Y8itC4jfQs/y03yE9uE+ANwsRX4Be5ff8Dgt3TfG2YeJ10KO8w69HymQL2/gAEfEq6E30qLRPAi08OcVHiYnXQE+G9qk+t4Vnp7mpCPEK6MXQPc8vLeye8mB7MX5DQKTAJ/350Ozk40VhE0XuNkzcBj0X+A08/aJcvvwc3ztA3AK9lgvq1t1+FV6koBuJWenmIMEGb+wJ3Es7giS8T42XBMRp0FOBeVdf0IU3qvLV5MQp0Eu+f0tv2IR3qptWMrt/ULsn3UDEn6B30EPoJel+pjpULlfaHtWMa9LNRPwFega9I92/lAM6MXN6w4OzAT5QRNYEPYJeQc9I9y3lsPKFylYtZn4u3WTEm6A30CPSfUr1UJVKrS9hZ/YOReLfSTcc8QboBfQEekO6PymXNFxvDOhG4jA/JAwvWHv0AHpBuh8pIeULZVwWfCLdjMRdsOZYe+n+ozwiO5ndyceMgw/WGGst3W+UBzU9fRKfD7ypmuS6dKMSx41/HWuLNZbuM8rjOnpsar1h2u8MReI3pBuXdAfWEGuJNZXuK8pnQtOYVuptdfTgk4Y+A2uGtaPxqa5lWnafum58Parpn0k3NlkbrBHWCmsm3TdUAJXOFLZrMXOWdxV6B6wF1iSVzr8o3R9USFQq1TbH9YSlTjVvShsgrKD2WAOshXQ/UCHV/MIiLg92qSPQEs8KXDvaL6HmqL30+lPUqhqN8QHDtPdFNeOyalRxswQF1BI1RW1RY+l1pqimKlfqW3TDjqjG/YLvNuzI9PdRO9QQtZReT4rqWJVq/RnVyDgz+HhwKPaztLm8CmqDGqFWqJn0ulGU4xobn+hX16+71XXsaCSqXwvzpQLmjhqgFqgJaiO9PhTlqobro5vVEW9PLG6NKTNcDfLTiZhbVNOvYq6YM+YuXX+K8pQmp2b6k6ncjrieiKgj45wKhW/VqbHvPkPAmDF2zAFzwZwwN+n6UpTvNHNydmM6U9hmmPZb6uhZVNfJ8zhbUNyRNjrGgLFgTBgbxoixYszSdaOowGtq+tRT2Vxxq2mldqnT6vfU0dZWR11cTuDs4SP1z1fU0fhrZdBbeH21+mcYVp2KG/d/Df4b/j/8GfxZ/B38XfwM/Cz8TPxs/A78LvxO/G7p+VPd6Z8T+LkG0yCJIwAAAABJRU5ErkJggg==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ninoo-nl
spec:
  selector:
    matchLabels:
      app: ninoo-nl
  replicas: 2
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: ninoo-nl
    spec:
      containers:
        - name: ninoo-nl
          image: joseluisq/static-web-server:2.35.0
          ports:
            - containerPort: 80
          volumeMounts:
            - name: ninoo-nl
              mountPath: /public/
          resources:
            requests:
              cpu: "10m"
              memory: "16Mi"
            limits:
              cpu: "10m"
              memory: "16Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          securityContext:
            allowPrivilegeEscalation: false
            # TODO
            # runAsNonRoot: true
            # capabilities:
            #   drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: ninoo-nl
          configMap:
            name: ninoo-nl
            items:
              - key: index.html
                path: index.html
              - key: style.css
                path: style.css
              - key: script.js
                path: script.js
              - key: linkedin.png
                path: linkedin.png
---
apiVersion: v1
kind: Service
metadata:
  name: ninoo-nl
spec:
  selector:
    app: ninoo-nl
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ninoo-nl
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ninoo.nl`, `www.ninoo.nl`)
      kind: Rule
      middlewares:
        - name: security-headers
      services:
        - name: ninoo-nl
          port: 80
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-headers
spec:
  headers:
    stsSeconds: 31536000
    stsIncludeSubdomains: true
    # stsPreload: true
    # generated with https://report-uri.com/home/generate
    contentSecurityPolicy: default-src 'none'; script-src 'self' https://www.youtube.com; style-src 'self'; img-src 'self'; frame-src https://youtube.com https://www.youtube.com; frame-ancestors 'none'; form-action 'none'; base-uri 'none'
    referrerPolicy: strict-origin
    contentTypeNosniff: true
    frameDeny: true
    # generated with https://www.permissionspolicy.com/
    permissionsPolicy: accelerometer=(), ambient-light-sensor=(), battery=(), camera=(), cross-origin-isolated=(), display-capture=(), document-domain=(), encrypted-media=(), execution-while-not-rendered=(), execution-while-out-of-viewport=(), geolocation=(), gyroscope=(), keyboard-map=(), magnetometer=(), microphone=(), midi=(), navigation-override=(), payment=(), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), sync-xhr=(), usb=(), web-share=(), xr-spatial-tracking=(), clipboard-read=(), clipboard-write=(), gamepad=(), speaker-selection=(), conversion-measurement=(), focus-without-user-activation=(), hid=(), idle-detection=(), interest-cohort=(), serial=(), sync-script=(), trust-token-redemption=(), window-placement=(), vertical-scroll=()
