# https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph/values.yaml
rook-ceph: # set values for wrapper/umbrella chart
  csi:
    enableRbdDriver: false
    enableCephfsDriver: true
    enableGrpcMetrics: false
    # Set to true to enable host networking for CSI CephFS and RBD nodeplugins. This may be necessary
    # in some network configurations where the SDN does not provide access to an external cluster or
    # there is significant drop in read/write performance.
    enableCSIHostNetwork: false
    # set to false to disable deployment of snapshotter container in CephFS provisioner pod.
    enableCephfsSnapshotter: true
    # set to false to disable deployment of snapshotter container in NFS provisioner pod.
    enableNFSSnapshotter: false
    # set to false to disable deployment of snapshotter container in RBD provisioner pod.
    enableRBDSnapshotter: false
    # set to false if the selinux is not enabled or unavailable in cluster nodes.
    enablePluginSelinuxHostMount: false
    # set to true to enable Ceph CSI pvc encryption support.
    enableCSIEncryption: false
