---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyberchef
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cyberchef
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cyberchef
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: cyberchef
          image: ghcr.io/gchq/cyberchef:11.1.0@sha256:0432df9ba52319fa5320c1fe72c6d4660bb0e24208580aa715b24cd3eb9d11bb
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            # readOnlyRootFilesystem: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
            requests:
              memory: 128Mi
              cpu: 100m
