---
apiVersion: v1
kind: Pod
metadata:
  name: cyberchef-test-connection
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  securityContext:
    runAsNonRoot: true
  containers:
    - name: wget
      image: cgr.dev/chainguard/curl:latest
      imagePullPolicy: Always
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
      command:
        - curl
      args:
        - -v
        - cyberchef:80
      resources:
        limits:
          memory: 16Mi
          cpu: 10m
        requests:
          memory: 16Mi
          cpu: 10m
  restartPolicy: Never
