---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeadm-config
  namespace: kube-system
data:
  ClusterConfiguration: |
    apiServer:
      certSANs:
        - kubernetes.oscarr.nl
        - kubernetes
        - kubernetes.default
        - kubernetes.default.svc
        - kubernetes.default.svc.cluster.local
        - fd00:beef::1
        - 10.96.0.1
        - localhost
        - ::1
        - 127.0.0.1
      extraArgs:
        authorization-mode: Node,RBAC
        oidc-client-id: kubernetes
        oidc-groups-claim: groups
        oidc-issuer-url: https://auth.oscarr.nl
        oidc-username-claim: preferred_username
      timeoutForControlPlane: 4m0s
    apiVersion: kubeadm.k8s.io/v1beta3
    certificatesDir: /etc/kubernetes/pki
    clusterName: kubernetes
    controlPlaneEndpoint: localhost:6000
    controllerManager: {}
    dns: {}
    etcd:
      local:
        dataDir: /var/lib/etcd
    imageRepository: registry.k8s.io
    kind: ClusterConfiguration
    kubernetesVersion: v1.29.2
    networking:
      dnsDomain: cluster.local
      serviceSubnet: 10.96.0.0/12,fd00:beef::/112
    scheduler: {}
