---
customization:
  systemExtensions:
    officialExtensions:
      - siderolabs/kata-containers
      - siderolabs/nvidia-open-gpu-kernel-modules-production
      - siderolabs/nvidia-container-toolkit-production
