---
customization:
  systemExtensions:
    officialExtensions:
      - siderolabs/kata-containers
      - siderolabs/qemu-guest-agent
      # - siderolabs/cloudflared
      # - siderolabs/tailscale
      # - siderolabs/wasmedge
