apiVersion: v2
name: element-wrapper
type: application
version: 1.0.0
dependencies:
  # Element Server Suite Community: Synapse, MAS, Element Web/Admin, MatrixRTC
  - name: matrix-stack
    version: 26.9.3
    repository: oci://ghcr.io/element-hq/ess-helm
