---
kind: Endpoints
apiVersion: v1
metadata:
  name: nas
subsets:
  - addresses:
      - ip: 100.64.0.12 # TODO fix this legacy ip
    ports:
      - port: 5001
        name: synology
      - port: 80
        name: web
---
kind: Service
apiVersion: v1
metadata:
  name: nas
spec:
  clusterIP: None
  ports:
    - port: 5001
      targetPort: 5001
      name: synology
    - port: 80
      targetPort: 80
      name: web
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nas
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`nas.oscarr.nl`)
      kind: Rule
      services:
        - name: nas
          port: 5001
    - match: Host(`oscarr.nl`, `0scar.nl`)
      kind: Rule
      services:
        - name: nas
          port: 80
